[dbaas_servers]
localhost ansible_connection=local
dbaas_worker ansible_host=192.168.8.183 ansible_user=dbaas

[saas_servers]
localhost ansible_connection=local
saas_worker ansible_host=192.168.8.183 ansible_user=dbaas

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_become_password=123456789
