---
- name: Déployer l'application Mongo Express
  community.docker.docker_container:
    name: "{{ instance_name }}"
    image: "mongo-express:latest"
    state: started
    restart_policy: always
    published_ports:
      - "{{ external_port }}:8081"
    env:
      ME_CONFIG_MONGODB_URL: "{{ mongo_url }}"
      ME_CONFIG_BASICAUTH_USERNAME: "{{ admin_email }}"
      ME_CONFIG_BASICAUTH_PASSWORD: "{{ admin_password }}"
