---
- name: Déployer l'application n8n Workflow Automation
  community.docker.docker_container:
    name: "{{ instance_name }}"
    image: "n8nio/n8n:latest"
    user: "root"
    state: started
    restart_policy: always
    networks:
      - name: "dynamix-network"
    env:
      N8N_LISTEN_ADDRESS: "0.0.0.0"
      N8N_SECURE_COOKIE: "false"
      WEBHOOK_URL: "http://{{ saas_domain }}/"
    volumes:
      - "/var/lib/saas/data/{{ instance_name }}:/home/node/.n8n"

