---
- name: Déployer l'application pgAdmin 4
  community.docker.docker_container:
    name: "{{ instance_name }}"
    image: "dpage/pgadmin4:latest"
    state: started
    restart_policy: always
    networks:
      - name: "dynamix-network"
    env:
      PGADMIN_DEFAULT_EMAIL: "{{ admin_email }}"
      PGADMIN_DEFAULT_PASSWORD: "{{ admin_password }}"

