---
- name: Déployer l'application phpMyAdmin
  community.docker.docker_container:
    name: "{{ instance_name }}"
    image: "phpmyadmin/phpmyadmin:latest"
    state: started
    restart_policy: always
    networks:
      - name: "dynamix-network"
    env:
      PMA_HOST: "{{ pma_host }}"
      PMA_PORT: "{{ pma_port | string }}"


